import type { Metadata } from "next"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import ConvexClientProvider from "@/components/ConvexClientProvider"
import IntlProvider from "@/providers/IntlProvider"
import localFont from "next/font/local"

export const metadata: Metadata = {
  title: "Telegram Clone",
  description: "Generated by create next app",
}

export const lucida = localFont({
  src: "./fonts/LucidaSansUnicode.ttf",
  variable: "--font-lucida",
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={lucida.variable}>
      <body className={`font-sans antialiased`}>
        <IntlProvider>
          <ClerkProvider
            signInFallbackRedirectUrl="/dashboard"
            signUpFallbackRedirectUrl="/dashboard"
          >
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </ClerkProvider>
        </IntlProvider>
      </body>
    </html>
  )
}
